### ISSUE TITLE
eleventy github action build failed

### ISSUE THREAD

**Issue by mofosyne** [mofosyne/call-to-action-map-static-site#1]
Got this

```
Run npm ci
npm ERR! Cannot read property '@11ty/eleventy' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2024-03-01T11_32_37_116Z-debug.log
Error: Process completed with exit code 1.
```

When 

```
      - name: Install packages
        run: npm ci
```

**Comment by mofosyne** [comment]
Solution is to update in build action 

```
    strategy:
      matrix:
        node-version: ['20.11.1']
```

so  that node is running in the most current version I'm using on my dev computer

```
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
```

This is because the eleventy package needs the latest node version
